[package]
name = "quizzer"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.66"
clap = { version = "4.0.18", features = ["derive"]}
rand = "0.9.2"
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0.87"
